services:
  stats-db:
    image: postgres:15.1-alpine
    container_name: EWM-stats-db
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - stats-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  ewm-db:
    image: postgres:15.1-alpine
    container_name: EWM-server-db
    ports:
      - "6542:5432"
    environment:
      POSTGRES_DB: ewm-server
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ewm-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  stats-db-data:
  ewm-db-data: